### ISSUE TITLE
Infinite notification

### ISSUE THREAD

**Issue by buzz-js** [buzz-js/buzz-notify#1]
Hide notification when clicking on it if it has infinite time

**Comment by m4tr1k** [comment]
@buzz-js Hi! I was trying the demo and the one that has infinite time (right bottom corner) hides when it is clicked. Am I not understanding what you want?

**Comment by kandarppatel28** [comment]
Hey @buzz-js , I have understood the requirement, can I work on it?

**Comment by kandarppatel28** [comment]
Hi @buzz-js , I checked the demo, and the infinite time notification hides when it is clicked

**Comment by buzz-js** [comment]
@m4tr1k @kandarppatel28 
Hey, thanks for your comment. Apparently there has been a mistake, the error has already been corrected. Sorry 😬
